version: '3.8'

services:
  dev-db:
    container_name: postgres
    image: postgres:13
    ports:
      - 5434:5432
    env_file:
      - ./.env
    networks:
      - freecodecamp
  test-db:
    container_name: test-postgres
    image: postgres:13
    ports:
      - 5435:5432
    env_file:
      - ./.env.test
    networks:
      - freecodecamp
networks:
  freecodecamp:
